create table CUSTOMER_COURSE_JOIN (
    ID int not null AUTO_INCREMENT,
    CUSTOMER_ID int not null,
    COURSE_ID int not null,
    PRIMARY KEY (ID),
    CONSTRAINT FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (`COURSE_ID`) REFERENCES `COURSE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);